### ISSUE TITLE
Test Runner crashes when changing Level and Version (and test results exists)

### ISSUE THREAD

**Issue by matthiaskoenig** [sbmlteam/sbml-test-suite#68]
This could be related to #67. 
If I ran some tests and then change the Level and Version in the Drop-Down Menu the GUI crashes. This is reproducible. Workaround is to go in the test output directory and delete all CSV, then one can change the Level and Version.

On ubuntu 18.04, using the downloaded deb package from the latest release.

**Comment by matthiaskoenig** [comment]
Just tried to run from console to get additional messages:
Many failing asserts.
```
SBML Test Runner:28046): GLib-CRITICAL **: 14:04:37.865: g_base64_encode_step: assertion 'in != NULL' failed

(SBML Test Runner:28046): GLib-CRITICAL **: 14:04:37.867: g_base64_encode_step: assertion 'in != NULL' failed

(SBML Test Runner:28046): GLib-CRITICAL **: 14:04:37.867: g_base64_encode_step: assertion 'in != NULL' failed

(SBML Test Runner:28046): GLib-CRITICAL **: 14:04:37.868: g_base64_encode_step: assertion 'in != NULL' failed

(SBML Test Runner:28046): GLib-CRITICAL **: 14:04:37.868: g_base64_encode_step: assertion 'in != NULL' failed

(SBML Test Runner:28046): GLib-CRITICAL **: 14:04:37.887: g_base64_encode_step: assertion 'in != NULL' failed

(SBML Test Runner:28046): GLib-CRITICAL **: 14:04:37.887: g_base64_encode_step: assertion 'in != NULL' failed

(SBML Test Runner:28046): GLib-CRITICAL **: 14:04:37.888: g_base64_encode_step: assertion 'in != NULL' failed

(SBML Test Runner:28046): GLib-CRITICAL **: 14:04:37.888: g_base64_encode_step: assertion 'in != NULL' failed

(SBML Test Runner:28046): GLib-CRITICAL **: 14:04:37.889: g_base64_encode_step: assertion 'in != NULL' failed

(SBML Test Runner:28046): GLib-CRITICAL **: 14:04:37.889: g_base64_encode_step: assertion 'in != NULL' failed

(SBML Test Runner:28046): GLib-CRITICAL **: 14:04:37.900: g_base64_encode_step: assertion 'in != NULL' failed

(SBML Test Runner:28046): GLib-CRITICAL **: 14:04:37.900: g_base64_encode_step: assertion 'in != NULL' failed
java.lang.IllegalArgumentException: Argument cannot be null
	at org.eclipse.swt.SWT.error(SWT.java:4518)
	at org.eclipse.swt.SWT.error(SWT.java:4452)
	at org.eclipse.swt.SWT.error(SWT.java:4423)
	at org.swtchart.internal.series.Series.setXSeries(Series.java:189)
	at org.sbml.testsuite.ui.MainWindow.addTimeSeriesChartForData(MainWindow.java:607)
	at org.sbml.testsuite.ui.MainWindow.addChartForData(MainWindow.java:555)
	at org.sbml.testsuite.ui.MainWindow.updatePlotsForSelection(MainWindow.java:3735)
	at org.sbml.testsuite.ui.MainWindow.access$700(MainWindow.java:109)
	at org.sbml.testsuite.ui.MainWindow$9.handleEvent(MainWindow.java:1087)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5581)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1363)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4834)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4415)
	at org.sbml.testsuite.ui.MainWindow.open(MainWindow.java:2854)
	at org.sbml.testsuite.ui.Program.main(Program.java:58)
```

**Comment by fbergmann** [comment]
that does seem odd ... could you please give me (just some csv files and your wrapper configuration) so i can reproduce it? It would also be good to know what version of the testrunner you are running (that would be in the about menu)

For me this seems to be working fine: 

![version 3.3.0](https://p194.p3.n0.cdn.getcloudapp.com/items/8LujvvXZ/Screen%20Recording%202020-05-29%20at%2003.18.47.17%20PM.gif?v=4b74a175a121fbf3d1cbbb6ebc2c5b0c)

**Comment by fbergmann** [comment]
I've looked at the other issue, and the other issue was something completely different (but that one is solved). I've checked out the runner on 18.04 and it works there for me too. To reproduce: 

    cd src/test-runner/testsuite-ui
    TESTRUNNER_IGNORE_ARCHIVE=true TESTRUNNER_IGNORE_HELP=true ant jar 
    TESTRUNNER_IGNORE_ARCHIVE=true TESTRUNNER_IGNORE_HELP=true ant start-linux-64
    
I do get gazillions of assertions ... but those are not thrown by us, but by glib ... so i'm not worried about those.

**Comment by matthiaskoenig** [comment]
I deleted the error messages from before, they were related to a different issue not related to the test runner. The errors I get are the following:
```
org.eclipse.swt.SWTException: Widget is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4537)
	at org.eclipse.swt.SWT.error(SWT.java:4452)
	at org.eclipse.swt.SWT.error(SWT.java:4423)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:502)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:439)
	at org.eclipse.swt.custom.StyledText.setText(StyledText.java:10105)
	at org.sbml.testsuite.ui.ProgressSection.setStatus(ProgressSection.java:153)
	at org.sbml.testsuite.ui.MainWindow.updateProgressSection(MainWindow.java:2065)
	at org.sbml.testsuite.ui.MainWindow.updateProgressSection(MainWindow.java:2082)
	at org.sbml.testsuite.ui.MainWindow.access$1100(MainWindow.java:109)
	at org.sbml.testsuite.ui.MainWindow$57.run(MainWindow.java:2056)
	at org.eclipse.swt.widgets.Display.timerProc(Display.java:5484)
	at org.eclipse.swt.internal.gtk.OS._g_main_context_iteration(Native Method)
	at org.eclipse.swt.internal.gtk.OS.g_main_context_iteration(OS.java:2133)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4413)
	at org.eclipse.swt.widgets.Display.release(Display.java:4470)
	at org.eclipse.swt.graphics.Device.dispose(Device.java:235)
	at org.sbml.testsuite.ui.MainWindow.open(MainWindow.java:2863)
	at org.sbml.testsuite.ui.Program.main(Program.java:58)
```
Using version 3.3.0 (the Ubuntu deb which is available as download).

Attached the CSV I have in my output folder
[sbscl-test-suite.zip](https://github.com/sbmlteam/sbml-test-suite/files/4705275/sbscl-test-suite.zip)

**Comment by matthiaskoenig** [comment]
Attached video of the issue
[2020-05-30 09-48-18.zip](https://github.com/sbmlteam/sbml-test-suite/files/4705286/2020-05-30.09-48-18.zip)

**Comment by matthiaskoenig** [comment]
I just rebuild with ant from the latest develop commit (6306a88a1f401756e52a4b608c5987f793fd5547
 https://github.com/sbmlteam/sbml-test-suite/commit/6306a88a1f401756e52a4b608c5987f793fd5547)

Using 
```
cd src/test-runner/testsuite-ui
TESTRUNNER_IGNORE_ARCHIVE=true TESTRUNNER_IGNORE_HELP=true ant jar 
TESTRUNNER_IGNORE_ARCHIVE=true TESTRUNNER_IGNORE_HELP=true ant start-linux-64
```
Now when changing level and version the GUI is not dying, but just freezing on the Refreshing results list ;) so some improvement.
![Screenshot from 2020-05-30 10-05-42](https://user-images.githubusercontent.com/900538/83323187-5cc08300-a25d-11ea-9ea6-c4ba9f680933.png)

**Comment by fbergmann** [comment]
and indeed there were some files in that results set, that were not parsable: 

![image](https://user-images.githubusercontent.com/949059/83331120-64e7e500-a294-11ea-8ece-7f830df3abb0.png)

should work now ... from master

**Comment by mhucka** [comment]
I will merge this change to branch `develop`.

**Comment by matthiaskoenig** [comment]
Perfect. Works like a charm. Thanks so much.
